const express = require("express");
const router = express.Router();
const {
  getInstructor,
  getStudent,
  getAdmin,
  addInstructor,
  addStudent,
  addAdmin,
  addInternship,
  addPlacement,
  getStudentByInstructor,
  getInstructorByEmailID,
  getStudentByprnno,
  getInternshipByInstructor,
  getInternshipByprnno,
  getPlacementByprnno,
  getPlacementByInstructor,
  getQuestionByprnno,
  getQuestionByInstructor,
  deleteAdmin,
  deleteInstructor,
  deleteStudent,
} = require("../controller/admin");
const { addBatch, deleteBatch } = require("../controller/instructor");
router
  .route("/:adminemailId/instructor")
  .get(getInstructor)
  .post(addInstructor);
router
  .route("/:adminemailId/admin")
  .get(getAdmin)
  .post(addAdmin);
router
  .route("/:adminemailId/student")
  .get(getStudent)
  .post(addStudent);
router
  .route("/:adminemailId/:prnNo/internship")
  .post(addInternship)
  .get(getInternshipByprnno);
router
  .route("/:adminemailId/:prnNo/placement")
  .post(addPlacement)
  .get(getPlacementByprnno);
router.route("/:adminemailId/:prnNo/question").get(getQuestionByprnno);
router
  .route("/:adminemailId/:instructoremailId")
  .get(getInstructorByEmailID)
  .delete(deleteInstructor);
router
  .route("/:adminemailId/:prnNo")
  .get(getStudentByprnno)
router.route("/:adminemailId/:prnNo/delete").delete(deleteStudent);
router
  .route("/:adminemailId/:instructoremailId/:prnNo")
  .get(getStudentByInstructor)
  .post(addBatch)
  .delete(deleteBatch);
  router
    .route("/:adminemailId/:instructoremailId/:prnNo/internship")
    .get(getInternshipByInstructor);
  router
    .route("/:adminemailId/:instructoremailId/:prnNo/placement")
    .get(getPlacementByInstructor);
  router
    .route("/:adminemailId/:instructoremailId/:prnNo/question")
    .get(getQuestionByInstructor);
router
    .route("/:adminemailId/:emailId")
    .delete(deleteAdmin);
module.exports = router;
